pipeline:
  build:
    image: node
    commands:
      # Install node_modules
      - npm install

      # Determine if webpack needs a rebuild.
      - git fetch origin
      - git checkout origin/staging config/webpack/build.json
      - git checkout development
      - npm run toggle-webpack
      - npm run build -- staging
    when:
      branch:
        exclude: [ production, staging, greenkeeper/* ]

  sitemap:
    image: node
    commands:
      npm run sitemap
    when:
      branch:
        exclude: [ production, staging, greenkeeper/* ]

  # Smoke tests
  lint:
    image: node
    commands:
      - npm run lint
    when:
      branch:
        exclude: [ production, staging, greenkeeper/* ]

  test - development:
    image: node
    commands:
      - npm test
    when:
      branch:
        exclude: [ production, staging, greenkeeper/* ]

  test - production:
    image: node
    commands:
      - npm test --production
    when:
      branch:
        exclude: [ production, staging, greenkeeper/* ]

  # Add to staging branch
  stage:
    image: node
    commands:
      - git config --global user.email "apps@nexus-stats.com"
      - git config --global user.name "nexus-ci"

      # Modify files as needed for staging build
      - sed -i '/\\/assets\\/bundles\\//d' .gitignore # Keep webpack builds
      - mv assets/.robots.txt assets/robots.txt # Make search engines ignore the staging site

      # Push changes from above and from dev branch
      - git add -A
      - git commit -m "Add staging builds"
      - bash build/stage.sh
    secrets: [ nexus_ci_token ]
    when:
      branch: development
      event: [ push ]

  # Build nexus-stats:staging image and push to dockerhub. Dockerhub will then
  # trigger a webhook on the staging server to redeploy.
  publish - staging:
    image: plugins/docker
    dockerfile: docker/app/prod/Dockerfile.staging
    context: docker/app/prod/
    repo: nexusstats/nexus-stats
    tags: staging
    no_cache: true
    secrets: [ docker_username, docker_password ]
    when:
      branch: staging
      event: [ push ]

  publish - development:
    image: plugins/docker
    dockerfile: docker/app/dev/Dockerfile
    context: docker/app/dev/
    repo: nexusstats/nexus-stats-dev
    no_cache: true
    secrets: [ docker_username, docker_password ]
    when:
      branch: staging
      event: [ push ]

  # Final release to production
  # TODO: Rebuild webpack without staging flag, push to repo, then build
  # nexus-stats:latest tag from that. Also add changelog and release generation.
  release:
    image: node
    commands:
      - git fetch --tags --quiet origin
      - npm run release
    secrets: [ gh_token ]
    when:
      branch: production
      event: [ push ]

services:
  mongodb:
    image: mongo
    when:
      branch:
        exclude: [ production, staging, greenkeeper/* ]
  redis:
    image: redis
    when:
      branch:
        exclude: [ production, staging, greenkeeper/* ]
